# Generated by Django 4.2.6 on 2023-10-23 14:25

import appointCareApp.models
import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientDisease', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatric', 'Pediatric')], max_length=50)),
                ('patientAge', models.PositiveIntegerField()),
                ('timeBooked', models.DateTimeField(default=datetime.datetime(2023, 10, 23, 14, 25, 20, 217533, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='hospitals', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='hospitals_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNumber', models.CharField(max_length=150)),
                ('profilePic', models.ImageField(default='user/default.png', upload_to=appointCareApp.models.upload_user_profiles, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointCareApp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_Image', models.ImageField(default='hospitals/mayoclinic.jpg', upload_to=appointCareApp.models.upload_to, verbose_name='image')),
                ('hospital_Location', models.CharField(max_length=60)),
                ('hospital_Slogan', models.CharField(blank=True, max_length=100)),
                ('hospital_Description', models.TextField()),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointCareApp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorImage', models.ImageField(default='hospitals/default.jpg', upload_to=appointCareApp.models.upload_to, verbose_name='image')),
                ('doctorName', models.CharField(max_length=50)),
                ('doctorSpeciality', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatric', 'Pediatric')], max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='appointCareApp.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointCareApp.hospital'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
