# Generated by Django 4.2.6 on 2023-10-19 12:42

import appointCareApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_Image', models.ImageField(default='hospitals/', upload_to=appointCareApp.models.upload_to, verbose_name='image')),
                ('hospital_Location', models.CharField(max_length=60)),
                ('hospital_Slogan', models.CharField(blank=True, max_length=100)),
                ('hospital_Description', models.TextField()),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HospitalDetail',
        ),
    ]
