# Generated by Django 4.2.6 on 2023-10-24 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 6, 58, 2, 140750, tzinfo=datetime.timezone.utc)),
        ),
    ]
