# Generated by Django 4.2.6 on 2023-10-18 09:33

import appointCareApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_Image',
            field=models.ImageField(default='hospitals/mayoclinic.jpg', upload_to=appointCareApp.models.upload_to, verbose_name='image'),
        ),
    ]
