# Generated by Django 4.2.6 on 2023-10-19 08:02

import appointCareApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0002_userprofile_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='user/', upload_to=appointCareApp.models.upload_to, verbose_name='image'),
        ),
    ]
