# Generated by Django 4.2.6 on 2023-10-19 13:43

import appointCareApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0002_hospitaldetails_delete_hospitaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorImage', models.ImageField(default='hospitals/', upload_to=appointCareApp.models.upload_to, verbose_name='image')),
                ('doctorName', models.CharField(max_length=50)),
                ('doctorSpeciality', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
