# Generated by Django 4.2.6 on 2023-10-23 15:15

import appointCareApp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0002_alter_hospital_options_alter_hospital_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalnotification',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='hospitalnotification',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointCareApp.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalnotification',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointCareApp.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patientDisease',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatric', 'Pediatric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 15, 15, 34, 21656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(default='user/default.png', upload_to=appointCareApp.models.upload_user_profiles, verbose_name='image'),
        ),
    ]
