# Generated by Django 4.2.6 on 2023-10-24 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0003_remove_hospitalnotification_booked_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospitals/')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 32, 26, 630294, tzinfo=datetime.timezone.utc)),
        ),
    ]
