# Generated by Django 4.2.6 on 2023-10-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0004_doctor_hospital_patientprofile_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
    ]
