# Generated by Django 4.2.6 on 2023-10-27 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0004_hospitallist_alter_booking_timebooked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalList',
        ),
        migrations.AlterField(
            model_name='booking',
            name='patientDisease',
            field=models.CharField(choices=[('general', 'General'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatric', 'Pediatric'), ('dentistry', 'Dentistry'), ('surgery', 'Surgery'), ('pharmacy', 'Pharmacy'), ('ct-scan', 'Ct-scan'), ('ultrasound', 'Ultrasound'), ('physiotherapy', 'Physiotherapy'), ('orthopaedics', 'Orthopaedics'), ('antenatal&postanalservices', 'Antenatal&postanalservices'), ('counselling', 'Counselling'), ('babywellclinics', 'Babywellclinics'), ('tBclinics', 'TBclinics'), ('laboratoryservices', 'Laboratoryservices'), ('curativeservices', 'Curativeservices'), ('occupationalsevices', 'Occupationalsevices'), ('maternity in-patient services with a word', 'Maternity in-patient services with a word')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 14, 12, 20, 788743, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctorsdetails',
            name='doctorSpeciality',
            field=models.CharField(choices=[('general', 'General'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatric', 'Pediatric'), ('dentistry', 'Dentistry'), ('surgery', 'Surgery'), ('pharmacy', 'Pharmacy'), ('ct-scan', 'Ct-scan'), ('ultrasound', 'Ultrasound'), ('physiotherapy', 'Physiotherapy'), ('orthopaedics', 'Orthopaedics'), ('antenatal&postanalservices', 'Antenatal&postanalservices'), ('counselling', 'Counselling'), ('babywellclinics', 'Babywellclinics'), ('tBclinics', 'TBclinics'), ('laboratoryservices', 'Laboratoryservices'), ('curativeservices', 'Curativeservices'), ('occupationalsevices', 'Occupationalsevices'), ('maternity in-patient services with a word', 'Maternity in-patient services with a word')], max_length=50),
        ),
    ]
