# Generated by Django 4.2.6 on 2023-10-27 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0004_alter_booking_timebooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointCareApp.hospital'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 7, 12, 41, 774064, tzinfo=datetime.timezone.utc)),
        ),
    ]
