# Generated by Django 4.2.6 on 2023-10-21 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0004_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 16, 25, 19, 900552, tzinfo=datetime.timezone.utc)),
        ),
    ]
