# Generated by Django 4.2.6 on 2023-10-27 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0005_alter_booking_hospital_alter_booking_timebooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 11, 36, 50, 560950, tzinfo=datetime.timezone.utc)),
        ),
    ]
