# Generated by Django 4.2.6 on 2023-10-21 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0005_alter_patientdetails_timebooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 16, 32, 32, 494768, tzinfo=datetime.timezone.utc)),
        ),
    ]
