# Generated by Django 4.2.6 on 2023-10-30 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0006_alter_booking_timebooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 5, 27, 41, 644214, tzinfo=datetime.timezone.utc)),
        ),
    ]
