# Generated by Django 4.2.6 on 2023-10-23 07:59

import appointCareApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0006_alter_patientdetails_timebooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdetails',
            name='doctorSpeciality',
            field=models.CharField(choices=[('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('pediatric', 'Pediatric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='hospital_Image',
            field=models.ImageField(default='hospitals/mayoclinic.jpg', upload_to=appointCareApp.models.upload_to, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
    ]
