# Generated by Django 4.2.6 on 2023-10-23 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointCareApp', '0007_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='patientContact',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='patientDoctor',
        ),
        migrations.AddField(
            model_name='booking',
            name='timeBooked',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 8, 10, 28, 500087, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
