# Generated by Django 4.2.6 on 2023-10-23 09:40

import appointCareApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointCareApp', '0007_alter_doctorsdetails_doctorspeciality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('booked_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctorsdetails',
            name='doctorImage',
            field=models.ImageField(default='hospitals/default.jpg', upload_to=appointCareApp.models.upload_to, verbose_name='image'),
        ),
    ]
